In [5]:
import sqlite3
import pandas as pd
from google.colab import files

# Function to display a table
def display_table(table_name, conn):
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    print(f"\n{table_name} Table:")
    display(df)

# Function to execute a JOIN query and display the result
def display_join_result(conn):
    print("\nArticles Read by Users (with JOIN):")
    join_query = '''
        SELECT USER.Email AS User_Email,
               ARTICLE.Title AS Article_Title,
               ARTICLE.Category AS Article_Category
        FROM ReadBy
        JOIN USER ON ReadBy.User_ID = USER.User_ID
        JOIN ARTICLE ON ReadBy.Article_ID = ARTICLE.Article_ID
    '''
    join_df = pd.read_sql_query(join_query, conn)
    display(join_df)

# Function to create tables and insert initial data
def create_and_insert_data(conn):
    cursor = conn.cursor()

    # Create tables
    cursor.execute('''CREATE TABLE IF NOT EXISTS AUTHOR (
                        Author_ID INTEGER PRIMARY KEY,
                        Name TEXT,
                        Birth_Date TEXT,
                        Sex TEXT,
                        Email TEXT
                    )''')

    cursor.execute('''CREATE TABLE IF NOT EXISTS AUTHOR_TEL (
                        Author_ID INTEGER,
                        Tel TEXT,
                        FOREIGN KEY (Author_ID) REFERENCES AUTHOR (Author_ID)
                    )''')

    cursor.execute('''CREATE TABLE IF NOT EXISTS ARTICLE (
                        Article_ID INTEGER PRIMARY KEY,
                        Title TEXT,
                        Category TEXT,
                        Publication_Date TEXT
                    )''')

    cursor.execute('''CREATE TABLE IF NOT EXISTS USER (
                        User_ID INTEGER PRIMARY KEY,
                        Subscription_Status TEXT,
                        Email TEXT,
                        Sex TEXT
                    )''')

    cursor.execute('''CREATE TABLE IF NOT EXISTS ReadBy (
                        User_ID INTEGER,
                        Article_ID INTEGER,
                        FOREIGN KEY (User_ID) REFERENCES USER (User_ID),
                        FOREIGN KEY (Article_ID) REFERENCES ARTICLE (Article_ID)
                    )''')

    # Insert data
    cursor.executemany('INSERT INTO AUTHOR (Name, Birth_Date, Sex, Email) VALUES (?, ?, ?, ?)', [
        ('Ahmet Yılmaz', '1970-03-12', 'M', 'ahmet.yilmaz@example.com'),
        ('Ayşe Demir', '1985-07-23', 'F', 'ayse.demir@example.com'),
        ('Mehmet Kaya', '1990-02-14', 'M', 'mehmet.kaya@example.com'),
        ('Fatma Çelik', '1995-11-05', 'F', 'fatma.celik@example.com'),
        ('Emre Şahin', '1988-09-30', 'M', 'emre.sahin@example.com')
    ])

    cursor.executemany('INSERT INTO ARTICLE (Title, Category, Publication_Date) VALUES (?, ?, ?)', [
        ('Yapay Zeka ve Gelecek', 'Teknoloji', '2024-01-01'),
        ('Sağlıklı Beslenme İpuçları', 'Yaşam', '2024-01-15'),
        ('Türk Tarihinde Dönüm Noktaları', 'Tarih', '2024-02-10'),
        ('Girişimcilik ve Yenilik', 'İş Dünyası', '2024-02-25'),
        ('Doğal Yaşamın Korunması', 'Çevre', '2024-03-05')
    ])

    cursor.executemany('INSERT INTO USER (Subscription_Status, Email, Sex) VALUES (?, ?, ?)', [
        ('Aktif', 'ali.kurt@example.com', 'M'),
        ('Pasif', 'zeynep.ak@example.com', 'F'),
        ('Aktif', 'murat.can@example.com', 'M'),
        ('Pasif', 'selin.tas@example.com', 'F'),
        ('Aktif', 'burak.uzun@example.com', 'M')
    ])

    cursor.executemany('INSERT INTO ReadBy (User_ID, Article_ID) VALUES (?, ?)', [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    ])

    conn.commit()
    print("Tables created and records inserted successfully!")

# CRUD Operations
def add_article(conn):
    title = input("Enter article title: ")
    category = input("Enter article category: ")
    publication_date = input("Enter publication date (YYYY-MM-DD): ")
    cursor = conn.cursor()
    cursor.execute("INSERT INTO ARTICLE (Title, Category, Publication_Date) VALUES (?, ?, ?)", (title, category, publication_date))
    conn.commit()
    print(f"Article '{title}' added successfully!")

def delete_user(conn):
    user_id = int(input("Enter the ID of the user to delete: "))
    cursor = conn.cursor()
    cursor.execute("DELETE FROM USER WHERE User_ID = ?", (user_id,))
    conn.commit()
    print(f"User with ID {user_id} deleted successfully!")

def update_article_category(conn):
    article_id = int(input("Enter the ID of the article to update: "))
    new_category = input("Enter the new category: ")
    cursor = conn.cursor()
    cursor.execute("UPDATE ARTICLE SET Category = ? WHERE Article_ID = ?", (new_category, article_id))
    conn.commit()
    print(f"Article with ID {article_id} updated successfully!")

# User menu to choose CRUD operations
def user_menu(conn):
    while True:
        print("\nChoose an operation:")
        print("1. Display USER Table")
        print("2. Display ARTICLE Table")
        print("3. Add an Article")
        print("4. Delete a User")
        print("5. Update an Article's Category")
        print("6. Display ReadBy Table (with JOIN)")
        print("7. Exit")

        choice = input("Enter your choice (1-7): ")

        if choice == '1':
            display_table("USER", conn)
        elif choice == '2':
            display_table("ARTICLE", conn)
        elif choice == '3':
            add_article(conn)
        elif choice == '4':
            delete_user(conn)
        elif choice == '5':
            update_article_category(conn)
        elif choice == '6':
            display_join_result(conn)
        elif choice == '7':
            print("Exiting the program. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 7.")

# Main function
def main():
    # Step 1: Connect to the database
    conn = sqlite3.connect("Online_Newspaper.db")
    print("Database connected successfully!")

    # Step 2: Create tables and insert data
    create_and_insert_data(conn)

    # Step 3: Start the user menu for CRUD operations
    user_menu(conn)

    # Step 4: Save and close connection
    conn.close()
    print("\nDatabase connection closed!")

# Run the main function
if __name__ == "__main__":
    main()

Database connected successfully!
Tables created and records inserted successfully!

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 5
Enter the ID of the article to update: 2
Enter the new category: Magazin
Article with ID 2 updated successfully!

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 1

USER Table:

    User_ID Subscription_Status                   Email Sex
0         1              Active       user1@example.com   M
1         2            Inactive       user2@example.com   F
2         3               Aktif    ali.kurt@example.com   M
3         4               Pasif   zeynep.ak@example.com   F
4         5               Aktif   murat.can@example.com   M
5         6               Pasif   selin.tas@example.com   F
6         7               Aktif  burak.uzun@example.com   M
7         8               Aktif    ali.kurt@example.com   M
8         9               Pasif   zeynep.ak@example.com   F
9        10               Aktif   murat.can@example.com   M
10       11               Pasif   selin.tas@example.com   F
11       12               Aktif  burak.uzun@example.com   M
12       13               Aktif    ali.kurt@example.com   M
13       14               Pasif   zeynep.ak@example.com   F
14       15               Aktif   murat.can@example.com   M
15       16               Pasif   selin.tas@example.com   F
16       17               Aktif  burak.uzun@example.com   M

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 2

ARTICLE Table:

    Article_ID                           Title    Category Publication_Date
0            1                   AI Revolution        Tech       2024-01-01
1            2                  Healthy Living     Magazin       2024-01-15
2            3           Yapay Zeka ve Gelecek   Teknoloji       2024-01-01
3            4      Sağlıklı Beslenme İpuçları       Yaşam       2024-01-15
4            5  Türk Tarihinde Dönüm Noktaları       Tarih       2024-02-10
5            6         Girişimcilik ve Yenilik  İş Dünyası       2024-02-25
6            7         Doğal Yaşamın Korunması       Çevre       2024-03-05
7            8           Yapay Zeka ve Gelecek   Teknoloji       2024-01-01
8            9      Sağlıklı Beslenme İpuçları       Yaşam       2024-01-15
9           10  Türk Tarihinde Dönüm Noktaları       Tarih       2024-02-10
10          11         Girişimcilik ve Yenilik  İş Dünyası       2024-02-25
11          12         Doğal Yaşamın Korunması       Çevre       2024-03-05
12          13           Yapay Zeka ve Gelecek   Teknoloji       2024-01-01
13          14      Sağlıklı Beslenme İpuçları       Yaşam       2024-01-15
14          15  Türk Tarihinde Dönüm Noktaları       Tarih       2024-02-10
15          16         Girişimcilik ve Yenilik  İş Dünyası       2024-02-25
16          17         Doğal Yaşamın Korunması       Çevre       2024-03-05

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 4
Enter the ID of the user to delete: 1
User with ID 1 deleted successfully!

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 4
Enter the ID of the user to delete: 1
User with ID 1 deleted successfully!

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 1

USER Table:

    User_ID Subscription_Status                   Email Sex
0         2            Inactive       user2@example.com   F
1         3               Aktif    ali.kurt@example.com   M
2         4               Pasif   zeynep.ak@example.com   F
3         5               Aktif   murat.can@example.com   M
4         6               Pasif   selin.tas@example.com   F
5         7               Aktif  burak.uzun@example.com   M
6         8               Aktif    ali.kurt@example.com   M
7         9               Pasif   zeynep.ak@example.com   F
8        10               Aktif   murat.can@example.com   M
9        11               Pasif   selin.tas@example.com   F
10       12               Aktif  burak.uzun@example.com   M
11       13               Aktif    ali.kurt@example.com   M
12       14               Pasif   zeynep.ak@example.com   F
13       15               Aktif   murat.can@example.com   M
14       16               Pasif   selin.tas@example.com   F
15       17               Aktif  burak.uzun@example.com   M

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 4
Enter the ID of the user to delete: 2
User with ID 2 deleted successfully!

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 1

USER Table:

    User_ID Subscription_Status                   Email Sex
0         3               Aktif    ali.kurt@example.com   M
1         4               Pasif   zeynep.ak@example.com   F
2         5               Aktif   murat.can@example.com   M
3         6               Pasif   selin.tas@example.com   F
4         7               Aktif  burak.uzun@example.com   M
5         8               Aktif    ali.kurt@example.com   M
6         9               Pasif   zeynep.ak@example.com   F
7        10               Aktif   murat.can@example.com   M
8        11               Pasif   selin.tas@example.com   F
9        12               Aktif  burak.uzun@example.com   M
10       13               Aktif    ali.kurt@example.com   M
11       14               Pasif   zeynep.ak@example.com   F
12       15               Aktif   murat.can@example.com   M
13       16               Pasif   selin.tas@example.com   F
14       17               Aktif  burak.uzun@example.com   M

Choose an operation:
1. Display USER Table
2. Display ARTICLE Table
3. Add an Article
4. Delete a User
5. Update an Article's Category
6. Display ReadBy Table (with JOIN)
7. Exit
Enter your choice (1-7): 7
Exiting the program. Goodbye!

Database connection closed!